# Build Stage
FROM node:18-alpine as build
WORKDIR /app
COPY site/package*.json ./
RUN npm install
COPY site/ .
RUN npm run build

# Production Stage
FROM nginx:alpine
RUN apk add --no-cache tzdata
COPY --from=build /app/dist /usr/share/nginx/html
# Copy custom nginx config
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
